### ISSUE TITLE
Structure "ocean monument" missing

### ISSUE THREAD

**Issue by Black-Hole** [jacobsjo/mc-datapack-map#10]
Minecraft call this "monument".
Other structures that are missing: "nether_fossil", "ruined_portal" (multiple variants).

**Comment by jacobsjo** [comment]
Mineshafts are also missing. Those structures have rather complicated placement code. See misode/deepslate#23. Given this map is mostly for datapacks and custom structures are mostly jigsaw, implementing those isn't really worth the effort. Sorry.

**Comment by Whitebrim** [comment]
> Mineshafts are also missing. Those structures have rather complicated placement code. See [misode/deepslate#23](https://github.com/misode/deepslate/pull/23). Given this map is mostly for datapacks and custom structures are mostly jigsaw, implementing those aren't really worth the effort. Sorry.

You should create a note on the site that those are missing intentionally.
I was trying to know how rare are ocean monuments in this datapack https://modrinth.com/datapack/dungeons-and-taverns-ocean-monument-overhaul, but I guess I have to do it in minecraft.

**Comment by jacobsjo** [comment]
@Whitebrim This datapack is a bit or an edge-case: Since it changes the ocean monument to a jigsaw structure, this map would be perfectly able to show the positions, its just hidden because the vanilla structure isn't supported. You can add the attached datapack to show all vanilla structures in the list. (it doesn't include names for the structures though, so its just called `monument`.

[show_all_structures.zip](https://github.com/user-attachments/files/20035079/show_all_structures.zip)

I'll try to figure out a better way to handle those unsupported structures in the future.
