### ISSUE TITLE
Feature suggestion: Color code too confusing and hard to read, add option to load custom biome colors

### ISSUE THREAD

**Issue by Delvin4519** [jacobsjo/mc-datapack-map#17]
The color codes are hard to understand without amidst or chunkbase colors. add an option to load a custom file with custom biome colors to easier view the map.

Right now custom datapacks can be loaded, so just need an extra option to overwrite biome colors with custom biome colors

In the first image the MC datapack map on the far left is hard to read, the others are much easier.
![image](https://github.com/jacobsjo/mc-datapack-map/assets/23464599/cc245d73-ba83-4bea-a8d1-5469bbdb98cd)

![image](https://github.com/jacobsjo/mc-datapack-map/assets/23464599/c77a4254-8b39-4cbd-b70c-61aede2aa2a6)
![image](https://github.com/jacobsjo/mc-datapack-map/assets/23464599/c6e09bea-3cdc-40f1-a464-a3f001df507c)

**Comment by jacobsjo** [comment]
Datapacks can define biome colors. That is not limited to biomes they themselfes add. Therefore, it is easy to make datapacks that override the vanilla biome colors. See https://github.com/jacobsjo/mc-datapack-map/wiki/Biome-and-Structure-Metadata for how to do that.

Since Amidst is licensed under GPL3 I can't use their biome colors wihout changing the license of this repository, which I do not want to do. You can of course use them is a separate datapack though.

I am also happy to accept pull requests with improved biome colors.
