### ISSUE TITLE
End Citys with Elytra and structure searching

### ISSUE THREAD

**Issue by Syntaxerrorontop** [jacobsjo/mc-datapack-map#50]
I was trying to find End cities with ships, but I couldn't find a single one. If I'm using this seed map, I have to create a new world with the same seed and then teleport to all the nearby End cities to find an Elytra. I would love it if you could add an option that will just show End cities with Elytra!

Additionally, something I found annoying was that if I wanted to view the structures in the End, it always told me to zoom in. Maybe you could change it so that the structures are always visible, making it easier to search for them!

(I used the online version)

**Comment by jacobsjo** [comment]
> I was trying to find End cities with ships, but I couldn't find a single one. 

Ships aren't that rare, if you couldn't find a single one you must have not been search a lot

> If I'm using this seed map, I have to create a new world with the same seed and then teleport to all the nearby End cities to find an Elytra.

You can use `/seed` to determine the seed of your current world, and then enter the seed in the map. No need to create a new world. You can also just use `/locate` to locate a nearby end-city ingame.

> I would love it if you could add an option that will just show End cities with Elytra!

That isn't feasible as it would require generating the entire structure

> Additionally, something I found annoying was that if I wanted to view the structures in the End, it always told me to zoom in. Maybe you could change it so that the structures are always visible, making it easier to search for them!

There are performance reasons why this limit exists. End cities often fail to generate because there isn't an island where they try to generate, so the map needs to calculate the terrain at all position, which isn't feasible when zoomed too far out.

I'm sorry I can't help you in this case. Good luck finding an Elytra!

**Comment by jacobsjo** [comment]
Also, for vanilla worldgen, I'd recommend you use [chunkbase](https://www.chunkbase.com/apps/seed-map), which does indicate which end cities have ships.
