### ISSUE TITLE
Dosent Work With Biomes O Plenty

### ISSUE THREAD

**Issue by TheBigSTN** [jacobsjo/mc-datapack-map#61]
I dont know if its a known issue but i tried to add the biomes o plenty jar and TerraBlender because its a depententy.
It found all the biomes it adds but it wont display them. 
i used the latest version of forge 1.20.1 of both Biomes o plenty and TerraBlender. this are the links to were i got them from:
https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty/download/5773031
https://www.curseforge.com/minecraft/mc-mods/terrablender/download/5378180
I hope its fixed and i think it a biomes o plenty bug but it is worth a shot

**Comment by jacobsjo** [comment]
TerraBlender is generally not supported. The map reimplements the vanilla worldgen code, so that it can read *datapacks* and show the terrain based on that. Mods that modify the the code - such as terrablender - can't be supported. Many other mods however just use the vanilla systems, and those are supported.

You might be interested in the [world preview mod](https://modrinth.com/mod/world-preview) instead.
